### ISSUE TITLE
empty check?

### ISSUE THREAD

**Issue by edsml-4c29515f** [ese-msc/introduction-to-python#18] opened 2021-09-01 15:38 UTC
Hi, 
I received the email that PyBryt has been upgraded so I re-try my solution, and I just found all the checks related to "empty" give an error anyway. Can you help me to check it?
![image](https://user-images.githubusercontent.com/88499904/131701074-4d131196-affb-4631-baca-c83a314cdce0.png)
![image](https://user-images.githubusercontent.com/88499904/131701110-5d6b2c1f-8281-429d-9503-ecd7be700c7b.png)
![image](https://user-images.githubusercontent.com/88499904/131701164-526bc6e0-f554-41be-b48e-617b604cab92.png)

**Comment by marijanbeg** [comment] 2021-09-01 21:35
Hi @edsml-4c29515f, thank you for raising this issue. This is a bug in PyBryt which causes that, in some cases, empty iterables are not correctly checked for equality.

This is now addressed in PyBryt PR (https://github.com/microsoft/pybryt/pull/109) and will be in the next release.

Thank you for your patience, and please raise further issues. Your feedback is very valuable to us. :)

**Comment by marijanbeg** [comment] 2021-09-02 10:51
Hi @edsml-4c29515f, thank you very much for your patience. PyBryt has been updated. Could you please restart your JupyterHub session and let us know if the problem is still present.

**Comment by edsml-4c29515f** [comment] 2021-09-08 14:55
Hi, sorry for the late response. I tested it again and I think the problem has been solved! Thanks a lot!

**Comment by marijanbeg** [comment] 2021-09-08 15:53
Great, thank you for letting us know @edsml-4c29515f.

Please feel free to raise further issues if we can help with anything else :)

**Closed by marijanbeg** 2021-09-08 15:53 UTC
Labels: PyBryt, awaiting-response
