### ISSUE TITLE
Question about exercise 2.2

### ISSUE THREAD

**Issue by acse-20449ecc** [ese-msc/introduction-to-python#12] opened 2021-08-09 05:23 UTC
Hi, here is part of my code to solve exercise 2.2

```
tlist = []
for i in range(11):
     t = 0 + i*(2*v0/g)/(10)
     tlist.append(t)
```

PyBryt said my tlist is wrong, therefore the ylist and displacement list are incorrect as well, yet the code 100.0% passed ok.grade() function, which made me confused. 

> MESSAGES:
>   - ERROR: Your tlist is wrong.
>   - ERROR: Your ylist is wrong.
>   - ERROR: Hmm... It seems your nested displacement list is wrong.

I also think these lines do generate 11 evenly spaced  𝑡  values ranging from 0 to 2𝑣0/𝑔 (including both ends)... Did I get something wrong?

**Comment by marijanbeg** [comment] 2021-08-09 08:38
Hi @acse-20449ecc, thank you for your question. I am sorry you encountered this issue - we are investigating it.

Could you please attempt to solve this exercise using list comprehensions and let us know what feedback PyBryt gives you?

**Comment by acse-20449ecc** [comment] 2021-08-09 09:57
Thank you for your reply :)
So I tried 

```
tlist = [i*dx for i in range(a)]
ylist = [v0*t-0.5*g*t**2 for t in tlist1]
```

And the outcome of these two lines are 100% approved by both PyBryt and ok.grade(). I also tried to print out the two tlist-s generated by different methods 

```
tlist_original = []
tlist = [i*dx for i in range(a)]

for i in range(11):
    t = 0 + i*(2*v0/g)/(10)
    tlist_original.append(t)
      
print(tlist)
print(tlist_original)
```
and I got

> [0.0, 0.02038735983690112, 0.04077471967380224, 0.061162079510703356, 0.08154943934760447, 0.1019367991845056, 0.12232415902140671, 0.14271151885830782, 0.16309887869520895, 0.18348623853211007, 0.2038735983690112]
> [0.0, 0.02038735983690112, 0.04077471967380224, 0.06116207951070336, 0.08154943934760447, 0.1019367991845056, 0.12232415902140673, 0.14271151885830785, 0.16309887869520895, 0.18348623853211007, 0.2038735983690112]

It can be seen that there are some slight differences in the last few digits of the decimal part of t elements( though I have no idea what causes these differences), guess that is why PyBrty gave me error messages while the ok.grade() accepted the final outcome.

**Comment by acse-20449ecc** [comment] 2021-08-09 10:16
( Sorry I forgot to paste these lines...

```
a = 11
dx = (2*v0/g)/(a-1)
```

**Comment by marijanbeg** [comment] 2021-08-09 13:39
Hi @acse-20449ecc, thank you very much for giving us more information.

We investigated this problem and discovered that it occurs because of the bug in PyBryt. More precisely, PyBryt does not take into account tolerances when checking iterables. This is now fixed and merged in PyBryt (https://github.com/microsoft/pybryt/pull/103) and will be in the next release. As soon as PyBryt is released, we will update JupyterHub. Thank you for your patience. (I keep this issue open until PyBryt is released and JupyterHub dependencies fixed.)

Thank you very much for your valuable feedback, and please do not hesitate to raise further issues.

**Comment by marijanbeg** [comment] 2021-09-01 09:28
Hi @acse-20449ecc, I can confirm that the PyBryt version has been upgraded to 0.1.9 on JupyterHub. Therefore, I am closing this issue now.

Thank you very much for your valuable feedback, and please do not hesitate to raise further issues.

**Closed by marijanbeg** 2021-09-01 09:28 UTC
Labels: bug, JupyterHub, PyBryt, waiting-PyBryt-release
