### ISSUE TITLE
JupyterHub browser access forbidden?

### ISSUE THREAD

**Issue by edsml-na506** [ese-msc/introduction-to-python#13] opened 2021-08-09 13:13 UTC
Hi I received the following error / issue after I allowed permission to access my GitHub account, when trying to access the course?
![image](https://user-images.githubusercontent.com/88665260/128711686-34adce2a-6b32-498b-9f34-dd240ba2f42b.png)

**Comment by edsml-na506** [comment] 2021-08-09 13:22
When I click the JupyterHub badge on this page: https://github.com/ese-msc/introduction-to-python I get the following error
![image](https://user-images.githubusercontent.com/88665260/128713017-47d405bc-1122-436b-9690-5462730b6729.png)

**Comment by marijanbeg** [comment] 2021-08-09 13:46
Hi @edsml-na506, thank you for reporting this issue. We will investigate this further and get back to you as soon as possible (@jrper, @tmbgreaves). Thank you for your patience.

**Comment by jrper** [comment] 2021-08-09 16:12
Hello @edsml-na506  I think this is down to you having been proactive and updating your username to your Imperial one already. We've been expecting you to use the username given in the original email we sent. I've added your current username to the system temporarily, could you confirm whether you are now able to connect?

**Comment by edsml-na506** [comment] 2021-08-09 19:13
Hi thanks for the quick reply, I just tried to log in to JH again. I initially thought it worked because it had asked me to verify my device with a 6-digit number code, for the first time, but when I correctly entered that in code, I still got the block below:
![image](https://user-images.githubusercontent.com/88665260/128761356-8f0d3f7f-afdc-4a21-8791-f452d876d7ba.png)

**Comment by edsml-na506** [comment] 2021-08-09 19:23
Is there a problem with my main na506 username? I thought that would be my default username for this course, per the instructions on the preinduction markdown site? Otherwise, let me know if I should change my username back to the original, to access the presessional materials. Thanks.

Also as another heads-up, I should report that when I go on this page - https://ese-msc.github.io/preinduction/edsml/markdown/EDSMLIntro.html Under the "Access to the course Jupyterhub site" the link for the instance results in this text error: 

<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>0g38RYQAAAACFWyG6pVgLQb1U7DFIEdQgTFRTRURHRTEzMTcARWRnZQ==

**Comment by edsml-na506** [comment] 2021-08-09 19:26
Is there a problem with my main na506 username? I thought that would be my default username for this course, per the instructions on the preinduction markdown site? Otherwise, let me know if I should change my username back to the original, to access the presessional materials. Thanks.

Also as another heads-up, I should report that when I go on this page - https://ese-msc.github.io/preinduction/edsml/markdown/EDSMLIntro.html Under the "Access to the course Jupyterhub site" the link for the instance results in this text error:

"Our services aren't available right now
We're working to restore all services as soon as possible. Please check back soon.
0g38RYQAAAACFWyG6pVgLQb1U7DFIEdQgTFRTRURHRTEzMTcARWRnZQ=="

**Comment by jrper** [comment] 2021-08-09 19:27
Thanks for both updates. I've made a further tweak to hopefully fix both issues, you should now be able to log in with either username (although they won't connect to the same account).

**Comment by edsml-na506** [comment] 2021-08-09 19:32
Success! Thanks @jrper for replying late in the evening! I seem to have working access to the dashboard:
![image](https://user-images.githubusercontent.com/88665260/128763498-fee6f02d-1f42-4fed-a371-ed936e3e9d01.png)

**Comment by jrper** [comment] 2021-08-09 19:34
Thanks, apologies for the slightly unclear error messages, and thankyou for raising the issue. I'm closing this issue now, reopen it if any problems reoccur.

**Closed by jrper** 2021-08-09 19:34 UTC
Labels: fix-required, JupyterHub

**Comment by marijanbeg** [comment] 2021-08-09 19:36
Hi @edsml-na506, thank you for confirming the problem is resolved, and thank you @jrper for addressing it.

**Comment by marijanbeg** [comment] 2021-08-09 19:38
For reference, the JupyterHub link at https://ese-msc.github.io/preinduction/edsml/markdown/EDSMLIntro.html is fixed as well as a part of this issue.

**Comment by edsml-na506** [comment] 2021-08-09 19:42
Thanks again both. I can confirm that both the GitHub badge link and the markdown instance link work for me at this time. Thanks
